<a href="https://colab.research.google.com/github/Varun0801/MachineLearning/blob/master/Naive_Bayes_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
weather=['Sunny','Sunny','Overcast','Rainy','Rainy','Rainy','Overcast','Sunny','Sunny','Rainy','Sunny','Overcast','Overcast','Rainy']

In [2]:
temp=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']

In [3]:
play=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [4]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
weather_encoded=le.fit_transform(weather)
print(weather_encoded)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


In [5]:
temp_encoded=le.fit_transform(temp)
label=le.fit_transform(play)
print("Temp:",temp_encoded)
print("Play:",label)

Temp: [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
Play: [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [6]:
import numpy as np
features=np.array([[2,1],[2,1],[0,1],[1,2],[1,0],[1,0],[0,0],[2,2],[2,0],[1,2],[2,2],[0,2],[0,1],[1,2]])

In [7]:
print(features)
print(label)

[[2 1]
 [2 1]
 [0 1]
 [1 2]
 [1 0]
 [1 0]
 [0 0]
 [2 2]
 [2 0]
 [1 2]
 [2 2]
 [0 2]
 [0 1]
 [1 2]]
[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [8]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(features,label)


GaussianNB(priors=None, var_smoothing=1e-09)

In [9]:
predicted= model.predict([[0,2]])

print("Predicted Value:", predicted)

Predicted Value: [1]
